<?php
namespace Crisjohn02\Encrypter;

use Illuminate\Support\ServiceProvider;

class EncrypterServiceProvider extends ServiceProvider
{

    public function boot()
    {

    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub

        $this->publishes([
                __DIR__ . '/config/config.php' => 'config/encrypter.php'
        ]);
    }
}
